<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Contact Information</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['fullname'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['useremail'];?></td>
		</tr>
		
		
		<tr>
			<td>Country:</td>
			<td><?= $data['countryname'];?></td>
		</tr>
		<tr>
			<td>Phone Number:</td>
			<td><?= $data['mobnum'];?></td>
		</tr>
		
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyname'];?></td>
		</tr>
		<tr>
			<td>Message:</td>
			<td><?= $data['message'];?></td>
		</tr>
<!-- 
		<tr>
			<td>Upload files:</td>
			<td><?= $data['phyob'];?></td>
			<td><?= $data['phyob'];?></td>
		</tr> -->
		</table>

</body>
</html>