<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Personal Details</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['name'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['email'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyname'];?></td>
		</tr>
		<tr>
			<td>Contact Number:</td>
			<td><?= $data['contactnumber'];?></td>
		</tr>
		<tr>
			<td>Address:</td>
			<td><?= $data['address'];?></td>
		</tr>
		<tr>
			<td>City:</td>
			<td><?= $data['city'];?></td>
		</tr>
		<tr>
			<td>State:</td>
			<td><?= $data['state'];?></td>
		</tr>
		<tr>
			<td colspan="2"><h3>Component Size</h3></td>
		</tr>
    	<tr>
			<td>Download File link:</td>
			<td><?= $data['upload_link'];?></td>
		</tr>
		<tr>
			<td>1mm to 100 mm:</td>
			<td><?=$data['1mm-to-100-mm'];?></td>
		</tr>
		<tr>
			<td>100 mm to 500 mm:</td>
			<td><?=$data['100-mm-to-500-mm'];?></td>
		</tr>
		<tr>
			<td>500 mm to 1000 mm:</td>
			<td><?=$data['500-mm-to-1000-mm'];?></td>
		</tr>
		<tr>
			<td>1000mm to 5000 mm:</td>
			<td><?=$data['1000mm-to-5000-mm'];?></td>
		</tr>
        <tr>
			<td>Large Objects and environments such as factories, ships and aircrafts</td>
			<td><?=$data['Large-Objects-and-environments-such-as-factories-ships-and-aircrafts']?></td>
		</tr>
		<tr>
			<td colspan="2"><h3>Accuracy Expectation</h3></td>
		</tr>
		
        <tr>
			<td>10-to-50 Micron-(.010-mm-to-.050-mm)</td>
			<td><?=$data['10-to-50-Micron-010-mm-to-050-mm'];?></td>
		</tr>
		<tr>
			<td>50-to-100-Micron-(.010-mm-to-.050-mm):</td>
			<td><?=$data['50-to-100-Micron-010-mm-to-050-mm'];?></td>
		</tr>
		<tr>
			<td>Above-100-micron-.1-mm</td>
			<td><?=$data['Above-100-micron-1-mm'];?></td>
		</tr>
		<tr>
			<td>I-am-not-sure</td>
			<td><?= $data['I-am-not-sure'];?></td>
		</tr>
		<tr>
			<td>measurement</td>
			<td><?= $data['ownmesare1'];?>to<?= $data['ownmesare2'];?></td>
		</tr>
		
		<tr>
			<td colspan="2"><h3>3D Scanner and Technology</h3></td>
		</tr>
        <tr>
			<td>Optical-3d-scanner-Gom-and-SolutioniX-3d-Scanner</td>
			<td><?= $data['Optical-3d-scanner-Gom-and-SolutioniX-3d-Scanner'];?></td>
		</tr>
        <tr>
			<td>Handheld-Metrology-3d-scanner-Freescan-UE7</td>
			<td><?= $data['Handheld-Metrology-3d-scanner-Freescan-UE7'];?></td>
		</tr>
        <tr>
			<td>Cost-effective-Multiutility-3D-scanner-Handheld-Tripod</td>
			<td><?= $data['Cost-effective-Multiutility-3D-scanner-Handheld-Tripod'];?></td>
		</tr>
        <tr>
			<td>Long-range-Laser-3D-scanner-Faro-Focus</td>
			<td><?= $data['Long-range-Laser-3D-scanner-Faro-Focus'];?></td>
		</tr>
        <tr>
			<td>Others-Please-mention</td>
			<td><?= $data['Others-Please-mention'];?><br><?= $data['message1'];?></td>
		</tr>
		<tr>
			<td colspan="2"><h3>Application</h3></td>
		</tr>
        <tr>
			<td>Just-3d-scanning-Point-Cloud-or-STL-files</td>
			<td><?= $data['Just-3d-scanning-Point-Cloud-or-STL-files'];?></td>
		</tr>
        <tr>
			<td>3D-Scan-to-CAD</td>
			<td><?= $data['3D-Scan-to-CAD'];?></td>
		</tr>
		 <tr>
			<td>3D-Inspection</td>
			<td><?= $data['3D-Inspection'];?></td>
		</tr>
		<tr>
			<td>My Application is specific</td>
			<td><?= $data['message2'];?></td>
		</tr>
		<tr>
			<td colspan="2"><h3>3D Scan your parts</h3></td>
		</tr>
		<tr>
			<td>Same-as-Company-address</td>
			<td><?= $data['your-location'];?></td>
		</tr>
		<tr>
			<td>Same-as-Company-address</td>
			<td><?= $data['nearby-location'];?></td>
		</tr>
		<tr>
			<td>Same-as-Company-address</td>
			<td><?= $data['my-location'];?></td>
		</tr>
		<tr>
			<td>Same-as-Company-address</td>
			<td><?= $data['Not-sure'];?></td>
		</tr>
		<tr>
			<td>Same-as-Company-address</td>
			<td><?= $data['message3'];?></td>
		</tr>
		<tr>
			<td colspan="2"><h3>3D Scanning location</h3></td>
		</tr>
        <tr>
			<td>Same-as-Company-address</td>
			<td><?= $data['Same-as-Company-address'];?></td>
		</tr>
        <tr>
			<td>Please-mention-the-address</td>
			<td><?= $data['Please-mention-the-address'];?></td>
		</tr>
		 <tr>
			<td>Address</td>
			<td><?= $data['Address'];?></td>
		</tr>
		 <tr>
			<td>city</td>
			<td><?= $data['city'];?></td>
		</tr>
		 <tr>
			<td>State</td>
			<td><?= $data['State'];?></td>
		</tr>
		<tr>
			<td>Pincode</td>
			<td><?= $data['pincode'];?></td>
		</tr>
	</table>

</body>
</html>