<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Contact Information</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['name'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['email'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyname'];?></td>
		</tr>
		<tr>
			<td>Contact Number:</td>
			<td><?= $data['contactnumber'];?></td>
		</tr>
		<tr>
			<td colspan="2"><h3>Technical Information</h3></td>
		</tr>
    	<tr>
			<td>Download File link:</td>
			<td><?= $data['upload_link'];?></td>
		</tr>
		<tr>
			<td>Best-fit-alignment:</td>
			<td><?=$data['Best-fit-alignment'];?></td>
		</tr>
		<tr>
			<td>RPS-alignment</td>
			<td><?=$data['RPS-alignment'];?></td>
		</tr>
		<tr>
			<td>Datum-alignment:</td>
			<td><?=$data['Datum-alignment'];?></td>
		</tr>
		<tr>
			<td>3-2-1-alignment:</td>
			<td><?=$data['3-2-1-alignment'];?></td>
		</tr>
        <tr>
			<td>Tolerance limit</td>
			<td><?=$data['tolerancelimit']?></td>
		</tr>
        <tr>
			<td>2D-Comparison</td>
			<td><?=$data['2D-Comparison'];?></td>
		</tr>
		<tr>
			<td>3D-Comparison:</td>
			<td><?=$data['3D-Comparison'];?></td>
		</tr>
		<tr>
			<td>Sheet-metal-Boundary-Comparison</td>
			<td><?=$data['Sheet-metal-Boundary-Comparison'];?></td>
		</tr>
		<tr>
			<td>Virtual-edge-comparison-measurment</td>
			<td><?= $data['Virtual-edge-comparison-measurment'];?></td>
		</tr>
        <tr>
			<td>Profile-projection-comparison</td>
			<td><?= $data['Profile-projection-comparison'];?></td>
		</tr>
        <tr>
			<td>Geometry-Deviation</td>
			<td><?= $data['Geometry-Deviation'];?></td>
		</tr>
        <tr>
			<td>3D-2D-Curve-Deviation</td>
			<td><?= $data['3D-2D-Curve-Deviation'];?></td>
		</tr>
        <tr>
			<td>Airfoil-Related-analysis-Airfoil-Twist</td>
			<td><?= $data['Airfoil-Related-analysis-Airfoil-Twist'];?></td>
		</tr>
        <tr>
			<td>pdf</td>
			<td><?= $data['pdf'];?></td>
		</tr>
        <tr>
			<td>pptx</td>
			<td><?= $data['pptx'];?></td>
		</tr>
        <tr>
			<td>xls</td>
			<td><?= $data['xls'];?></td>
		</tr>
		
		
	</table>

</body>
</html>