<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Contact Information from Figure 4 Standalone Printer</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['name'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['email'];?></td>
		</tr>
		<tr>
			<td>Company Number:</td>
			<td><?= $data['contactnumber'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyname'];?></td>
		</tr>
			<tr>
			<td>Company Address:</td>
			<td><?= $data['companyaddress'];?></td>
		</tr>
		

		
	</table>

</body>
</html>