<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Contact Information from SOLUTIONIX C500</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['name'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['email'];?></td>
		</tr>
		<tr>
			<td>Company Number:</td>
			<td><?= $data['contactnumber'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyname'];?></td>
		</tr>
		<tr>
			<td>Do you also need GST no included in the quote?</td>
			<td><?= $data['home'];?></td>
		</tr>
		<tr>
			<td>GST Number</td>
			<td><?= $data['gstnumber'];?></td>
		</tr>
		<tr>
			<td>Scanner Series</td>
			<td><?= $data['demo'];?></td>
		</tr>
		<tr>
			<td>Do you also need a quote for Geomagic software?</td>
			<td><?= $data['quote'];?></td>
		</tr>
		<tr>
			<td>Need quote for : </td>
			<td><?= $data['geomagicsoftware'];?></td>
		</tr>
		

		
	</table>

</body>
</html>