<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Contact Information from Freescan UE7</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['name'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['email'];?></td>
		</tr>
		<tr>
			<td>Phone Number:</td>
			<td><?= $data['contactnumber'];?></td>
		</tr>
	
		<tr>
			<td>File Format Required</td>
			<td><?= $data['demo'];?></td>
		</tr>
		<tr>
			<td>Modelling Technique</td>
			<td><?= $data['modellingTech'];?></td>
		</tr>
			<tr>
			<td>Component Size</td>
			<td><?= $data['ComponentSize'];?></td>
		</tr>
		<tr>
			<td>Accuracy Expectation</td>
			<td><?= $data['accuracyExpectation'];?></td>
		</tr>
		<tr>
			<td>Download File link</td>
			<td><?= $data['upload_link'];?></td>
		</tr>
		

		
	</table>

</body>
</html>