<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Webinar Contact Information</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['cadName'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['cadEmail'];?></td>
		</tr>
		<tr>
			<td>Contact Number:</td>
			<td><?= $data['cadContnum'];?></td>
		</tr>
		<tr>
			<td>Location:</td>
			<td><?= $data['cadLocation'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['cadCompanyname'];?></td>
		</tr>
		</table>

</body>
</html>