<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Contact Information</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['name'];?></td>
		</tr>
		<tr>
			<td>Mobile:</td>
			<td><?= $data['contactnumber'];?></td>
		</tr>
		<tr>
			<td> Company Email:</td>
			<td><?= $data['email'];?></td>
		</tr>
		
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyname'];?></td>
		</tr>
		<tr>
			<td>Do you have a 3d scanner in-house?</td>
			<td><?= $data['home'];?></td>
		</tr>
		<tr>
			<td>Do you need a demo during the evaluation?</td>
			<td><?= $data['demo'];?></td>
		</tr>
		<tr>
			<td>Do you also need a quote for Geomagic Design X Essential?</td>
			<td><?= $data['quote'];?></td>
		</tr>
		

		
	</table>

</body>
</html>