<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Webinar Contact Information</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['nameweb'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['emailweb'];?></td>
		</tr>
		<tr>
			<td>Contact Number:</td>
			<td><?= $data['contactnumberweb'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyweb'];?></td>
		</tr>
		</table>

</body>
</html>