<!DOCTYPE html>
<html>

<body>
    <table>
        <tr>
            <td colspan="2">
                <h3><?= $data['eventplace']; ?></h3>
            </td>
        </tr>
        <tr>
            <td>Title:</td>
            <td>
                <?= $data['title']; ?>
            </td>
        </tr>
        <tr>
            <td>First Name:</td>
            <td>
                <?= $data['fname']; ?>
            </td>
        </tr>
        <tr>
            <td>Last Name:</td>
            <td>
                <?= $data['lname']; ?>
            </td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>
                <?= $data['email']; ?>
            </td>
        </tr>
        <tr>
            <td>Designation:</td>
            <td>
                <?= $data['designation']; ?>
            </td>
        </tr>
        <tr>
            <td>Mobile no:</td>
            <td>
                <?= $data['number']; ?>
            </td>
        </tr>
        <tr>
            <td>Company Name:</td>
            <td>
                <?= $data['cname']; ?>
            </td>
        </tr>
        <tr>
            <td>Address:</td>
            <td>
                <?= $data['address']; ?>
            </td>
        </tr>
        <tr>
            <td>Country:</td>
            <td>
                <?= $data['country']; ?>
            </td>
        </tr>


        <tr>
            <td>State:</td>
            <td>
                <?= $data['state']; ?>
            </td>
        </tr>
        <tr>
            <td>City:</td>
            <td>
                <?= $data['city']; ?>
            </td>
        </tr>
        <tr>
            <td>Pin:</td>
            <td>
                <?= $data['pin']; ?>
            </td>
        </tr>
        <tr>
            <td>Website:</td>
            <td>
                <?= $data['website']; ?>
            </td>
        </tr>
    </table>

</body>

</html>