<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Book A Demo</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['nameweb'];?></td>
		</tr>
		<tr>
			<td>Contact Number:</td>
			<td><?= $data['contactnumberweb'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyweb'];?></td>
		</tr>
		<tr>
			<td>Demo Date:</td>
			<td><?= $data['date'];?></td>
		</tr>
		</table>

</body>
</html>