<!DOCTYPE html>
<html>

<body>
    <table>
        <tr>
            <td colspan="2">
                <h3>Geomagic Design X</h3>
            </td>
        </tr>
        <tr>
            <td>Full Name:</td>
            <td>
                <?= $data['name']; ?>
            </td>
        </tr>
        <tr>
            <td>Company Name:</td>
            <td>
                <?= $data['company_name']; ?>
            </td>
        </tr>
        <tr>
            <td>Job Title:</td>
            <td>
                <?= $data['job_title']; ?>
            </td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>
                <?= $data['email']; ?>
            </td>
        </tr>
        <tr>
            <td>Country:</td>
            <td>
                <?= $data['country1']; ?>
            </td>
        </tr>
        <tr>
            <td>Version:</td>
            <td>
                <?= $data['Version']; ?>
            </td>
        </tr>
        <tr>
            <td>Primary Application:</td>
            <td>
                <?= $data['Application']; ?>
            </td>
        </tr>


        <tr>
            <td>
                <h3>Additional Support Needed:</h3>
            </td>
            <td>
                <?= $data['free']; ?>
            </td>
            <td>
                <?= $data['Comparison']; ?>
            </td>
            <td>
                <?= $data['Other']; ?>
            </td>
        </tr>

        <tr>
            
        </tr>

        <tr>
            <td>Specify:</td>
            <td>
                <?= $data['Specify']; ?>
            </td>
        </tr>


        <tr>
            <td>Preferred Contact Method:</td>
            <td>
                <?= $data['eemail']; ?>
            </td>
            <td>
                <?= $data['phonee']; ?>
            </td>
        </tr>
        <tr>
            <td>Additional Comments or Requirements:</td>
            <td>
                <?= $data['Additional']; ?>
            </td>
        </tr>


    </table>

</body>

</html>