<!DOCTYPE html>
<html>
<body>
	<table>
		<tr>
			<td colspan="2"><h3>Contact Information</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['fname'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['newcompanyname'];?></td>
		</tr>
		<tr>
			<td>Contact Number:</td>
			<td><?= $data['contnum'];?></td>
		</tr>
		<tr>
			<td>Geomagic Product</td>
			<td><?= $data['selectProduct'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['newemail'];?></td>
		</tr>
		<tr>
			<td>Quantity:</td>
			<td><?= $data['quantity'];?></td>
		</tr>
		<tr>
		    <td>Licence Type</td>
		    <td><?= $data['licence_type'];?></td>
		</tr>
		<tr>
		    <td>Demo or Evaluation:</td>
		    <td><?= $data['demoqty'];?></td>
		</tr>
	</table>

</body>
</html>