<!DOCTYPE html>
<html>

<body>
    <table>
        <tr>
            <td colspan="2">
                <h3>Personal Details</h3>
            </td>
        </tr>
        <tr>
            <td>Full Name:</td>
            <td>
                <?= $data['name']; ?>
            </td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>
                <?= $data['email']; ?>
            </td>
        </tr>
        <tr>
            <td>Phone Number:</td>
            <td>
                <?= $data['phone']; ?>
            </td>
        </tr>
        <tr>
            <td>Company Name:</td>
            <td>
                <?= $data['company']; ?>
            </td>
        </tr>
        <tr>
            <td>Address:</td>
            <td>
                <?= $data['address']; ?>
            </td>
        </tr>
        <tr>
            <td>State:</td>
            <td>
                <?= $data['state1']; ?>
            </td>
        </tr>
        <tr>
            <td>City:</td>
            <td>
                <?= $data['city1']; ?>
            </td>
        </tr>
        <tr>
            <td>Country:</td>
            <td>
                <?= $data['country1']; ?>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <h3>Types of 3D Scanner:</h3>
            </td>

        </tr>
        <tr>
            <td colspan="2">
                <h5>(Let us know if you have any specific scanner type in mind ) </h5>
            </td>
        </tr>
        <tr>
            <td>
                Optical 3D Scanning (Structured light):</td>
            <td>
                <?= $data['Structuredlight']; ?>
            </td>
        </tr>
        <tr>
            <td>
                Industrial Handheld 3D Scanner (Metrology Grade):</td>
            <td>
                <?= $data['MetrologyGrade']; ?>
            </td>
        </tr>
        <tr>
            <td>
                Colour Handheld 3D Scanner:</td>
            <td>
                <?= $data['10to50Micron']; ?>
            </td>
        </tr>
        <tr>
            <td>Robot Mounted 3D scanner (Automated):</td>
            <td>
                <?= $data['50to100Micron']; ?>
            </td>
        </tr>
        <tr>
            <td>Handheld 3D Scanning With Photogrammetry:</td>
            <td>
                <?= $data['100-micron']; ?>
            </td>
        </tr>
        <tr>
            <td>
                Closed frame Desktop 3D scanner:</td>
            <td>
                <?= $data['Myaccuracy']; ?>
            </td>
        </tr>
        <tr>
            <td>Laser Arm-Based 3D Scanning:</td>
            <td>
                <?= $data['Imnot']; ?>
            </td>
        </tr>
        <tr>
            <td>Long Range 3D Scanning(Lidar) :</td>
            <td>
                <?= $data['SpecificAccuracy'] ?>
            </td>
        </tr>
        <tr>
            <td>I am not sure, Need Consultation:</td>
            <td>
                <?= $data['ComponentName'] ?>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <h3>Accuracy Requirements</h3>
            </td>

        </tr>
        <tr>
            <td colspan="2">
                <h4>(Please specify the level of accuracy you require from the 3D
                    scanning process ) </h4>
            </td>
        </tr>
        <tr>
            <td> 10 to 20 micron (.01 mm to .02 mm) :</td>
            <td>
                <?= $data['checkbox1']; ?>
            </td>
        </tr>
        <tr>
            <td>
                20 to 50 micron
                (.02 mm to .05 mm):</td>
            <td>
                <?= $data['checkbox2']; ?>
            </td>
        </tr>
        <tr>
            <td>
                50 to 100 micron
                (.05 mm to .1 mm):</td>
            <td>
                <?= $data['checkbox3']; ?>
            </td>
        </tr>
        <tr>
            <td>
                Above 100 microns (>.1 mm)</td>
            <td>
                <?= $data['checkbox4']; ?>
            </td>
        </tr>
        <tr>
            <td>My expected accuracy is more than 1mm:</td>
            <td>
                <?= $data['checkbox5']; ?>
            </td>
        </tr>

        <tr>
            <td>
                I'm not sure:
            </td>
            <td>
                <?= $data['checkbox6']; ?>
            </td>

        </tr>
        <tr>
            <td colspan="2">
                <h3>What object do you want to 3D Scan?</h3>
            </td>
        </tr>

        <tr>
            <td> Vehicles and vehicle components (Such as sheet metal, Die casting parts, vehicle assembly and frame ):
            </td>
            <td>
                <?= $data['checkbox7']; ?>
            </td>
        </tr>
        <tr>
            <td>Industrial plastic components:</td>
            <td>
                <?= $data['checkbox8']; ?>
            </td>
        </tr>
        <tr>
            <td>Human body:</td>
            <td>
                <?= $data['checkbox9']; ?>
            </td>
        </tr>
        <tr>
            <td>Building Factory and Environment:</td>
            <td>
                <?= $data['checkbox10']; ?>
            </td>
        </tr>
        <tr>
            <td>Other (Please specify the size of the objects):</td>
            <td>
                <?= $data['checkbox11']; ?>
            </td>
        </tr>



        <tr>
            <td colspan="2">
                <h3>Application purpose:</h3>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <h5>(Please select below post 3D Scan Application ):</h5>
            </td>
        </tr>
        <tr>
            <td>3D Reverse Engineering:</td>
            <td>
                <?= $data['Engineering']; ?>
            </td>
        </tr>
        <tr>
            <td>3D Inspection:</td>
            <td>
                <?= $data['Inspection']; ?>
            </td>
        </tr>
        <tr>
            <td>3D Printing:</td>
            <td>
                <?= $data['Scanning']; ?>
            </td>
        </tr>

        <tr>
            <td>Medical Modeling:</td>
            <td>
                <?= $data['ComponentPickup1']; ?>
            </td>
        </tr>
        <tr>
            <td>Education:</td>
            <td>
                <?= $data['Locationdifferent']; ?>
            </td>
        </tr>
        <tr>
            <td>
                Animation</td>
            <td>
                <?= $data['IfOnsite']; ?>
            </td>
        </tr>

        <tr>
            <td> BIM & Factory modelling:</td>
            <td>
                <?= $data['PreferredDate']; ?>
            </td>
        </tr>

        <tr colspan="2">
            <td>
                <h3 style="color:rgba(255, 138, 0, 1);">
                    Appointment
                </h3>
            </td>
        </tr>

        <tr colspan="2">
            <td>
                <h3>
                    Do you need the demo?
                </h3>
            </td>
        </tr>
        <tr>
            <td>Yes:</td>
            <td>
                <?= $data['form5-yes']; ?>
            </td>
        </tr>
        <tr>
            <td>No:</td>
            <td>
                <?= $data['form5-no']; ?>
            </td>
        </tr>

        <tr colspan="2">
            <td>
                <h3>
                    if Yes
                </h3>
            </td>
        </tr>

        <tr>
            <td>Online:</td>
            <td>
                <?= $data['Online']; ?>
            </td>
        </tr>

        <tr>
            <td>Onsite:</td>
            <td>
                <?= $data['Onsite']; ?>
            </td>
        </tr>

        <tr colspan="2">
            <td>
                <h3>
                    Do you need the formal quote?
                </h3>
            </td>
        </tr>

        <tr>
            <td>Yes:</td>
            <td>
                <?= $data['form5-yes1']; ?>
            </td>
        </tr>

        <tr>
            <td>No:</td>
            <td>
                <?= $data['form5-no1']; ?>
            </td>
        </tr>

        <tr>
            <td>Same as the Company address & GST no filled in on the first page:</td>
            <td>
                <?= $data['inside-content']; ?>
            </td>
        </tr>
        <tr>
            <td>No:</td>
            <td>
                <?= $data['inside-content1']; ?>
            </td>
        </tr>
        <tr>
            <td>Full Name:</td>
            <td>
                <?= $data['form5-name']; ?>
            </td>
        </tr>
        <tr>
            <td>State:</td>
            <td>
                <?= $data['form5-state']; ?>
            </td>
        </tr>
        <tr>
            <td>City:</td>
            <td>
                <?= $data['form5-city']; ?>
            </td>
        </tr>
        <tr>
            <td>GST Number:</td>
            <td>
                <?= $data['form5-gst']; ?>
            </td>
        </tr>

    </table>

</body>

</html>