<!DOCTYPE html>
<html>
<body>
	<table>
	    <tr>
			<td colspan="2"><h3>Select Type</h3></td>
		</tr>
		<tr>
			<td>Type:</td>
			<td><?= $data['chooseOne'];?></td>
		</tr>
		<tr>
			<td colspan="2"><h3>Contact Information</h3></td>
		</tr>
		<tr>
			<td>Name:</td>
			<td><?= $data['name'];?></td>
		</tr>
		<tr>
			<td>Email:</td>
			<td><?= $data['email'];?></td>
		</tr>
		<tr>
			<td>Contact Number:</td>
			<td><?= $data['contactNumber'];?></td>
		</tr>
		<tr>
			<td>Addess:</td>
			<td><?= $data['address'];?></td>
		</tr>
		<tr>
			<td>Company Name:</td>
			<td><?= $data['companyName'];?></td>
		</tr>
		<tr>
			<td>Download File link</td>
			<td><?= $data['upload_link'];?></td>
		</tr>
		
		<tr>
			<td>File Name:</td>
			<td><?=$data['file_name'];?></td>
		</tr>
		<tr>
			<td>Material Selected:</td>
			<td><?=$data['materialSelect'];?></td>
		</tr>
		<tr>
			<td>Microns:</td>
			<td><?=$data['microns'];?></td>
		</tr>
		<tr>
			<td>quantity:</td>
			<td><?=$data['quantity'];?></td>
		</tr>
			<td>Note:</td>
			<td><?=$data['note'];?></td>
		</tr>
		</tr>
			<td>Shipping Details:</td>
			<td><?=$data['shipping'];?></td>
		</tr>
	</table>

</body>
</html>